const january = [
  ["Alexandra", "Karina", "Ábel", "Makar", "Karin", "Kara", "Sandra", "Saša"],
  ["Daniela", "Danila", "Danuta", "Genovéva", "Radmila"],
  [
    "Drahoslav",
    "Drahoľub",
    "Drahomil",
    "Drahoň",
    "Drahoš",
    "Duchoslav",
    "León",
    "Títus",
    "Drahoľuba",
    "Drahomila",
    "Duchoslava",
    "Leóna",
    "Leónia",
  ],
  ["Andrea", "Artúr"],
  ["Antónia", "Melchior", "Melichar", "Menhard"],
  [
    "Bohuslava",
    "Attila",
    "Lucián",
    "Bohuna",
    "Boleslava",
    "Božislava",
    "Luciána",
  ],
  ["Severín", "Čestmír", "Pravomil", "Čestmíra", "Pravomila", "Severína"],
  [
    "Alexej",
    "Alex",
    "Domoľub",
    "Julián",
    "Pravoľub",
    "Vladan",
    "Vladen",
    "Alexia",
    "Pravoľuba",
    "Vladana",
    "Vladena",
  ],
  ["Dáša", "Agatón", "Dalimil", "Dalimír", "Dalimila", "Dalimíra"],
  ["Malvína", "Honorát", "Tasilo", "Honoráta"],
  ["Ernest", "Arkád", "Arnošt", "Arkádia", "Arnoštka", "Erna", "Ernestína"],
  [
    "Rastislav",
    "Čistomil",
    "Čistoslav",
    "Rastic",
    "Rastimír",
    "Ratislav",
    "Vidor",
    "Čistomila",
    "Čistoslava",
    "Rastislava",
    "Ratislava",
  ],
  ["Radovan", "Hilár", "Uriáš", "Uriel", "Hilária", "Radovana"],
  ["Dobroslav", "Dobrotín", "Domoslav", "Loránt", "Múdroslav", "Domoslava"],
  ["Kristína"],
  ["Nataša", "Sofia"],
  ["Bohdana", "Priskus", "Piroška", "Priska"],
  ["Drahomíra", "Mário", "Sára", "Márius", "Dúbravka"],
  [
    "Dalibor",
    "Fabián",
    "Fábius",
    "Sebastián",
    "Šebastián",
    "Fábia",
    "Fabiána",
    "Fabiola",
    "Sebastiána",
  ],
  ["Vincent", "Vincencia"],
  [
    "Zora",
    "Dorián",
    "Sírius",
    "Slavoľub",
    "Slavomil",
    "Zoran",
    "Auróra",
    "Cyntia",
    "Doriána",
    "Sinda",
    "Slavomila",
    "Zorana",
    "Zara",
    "Aylin",
  ],
  ["Miloš", "Miloň", "Selma"],
  ["Timotej", "Ctiboh", "Timotea"],
  ["Gejza", "Saul", "Šavol"],
  [
    "Tamara",
    "Tamia",
    "Polykarp",
    "Slavibor",
    "Slavislav",
    "Slaviboj",
    "Slavoboj",
    "Svätoboj",
    "Svätobor",
    "Xenofón",
    "Žarko",
    "Polykarpa",
  ],
  ["Bohuš", "Pribislav", "Pribiš"],
  ["Alfonz", "Manfréd", "Alfonzia"],
  ["Gašpar", "Pribina"],
  ["Ema", "Jasna"],
  ["Emil", "Emilián", "Emiliána", "Marika"],
];

const february = [
  ["Tatiana", "Hynek", "Trifon", "Táňa", "Girron", "Tanya"],
  ["Erik", "Erika", "Aida"],
  ["Blažej", "Celerín", "Celerína"],
  ["Veronika", "Nika", "Verena", "Verona"],
  ["Agáta", "Moderát", "Modest", "Leda", "Moderáta", "Modesta"],
  ["Dorota", "Dorisa", "Titanila"],
  ["Vanda", "Romuald"],
  ["Zoja(Lejla)", "Aranka", "Zoe"],
  ["Zdenko", "Rainold", "Rinaldo", "Zdeno", "Apolena", "Apoliena", "Apolónia"],
  ["Gabriela", "Scholastika", "Školastika"],
  ["Dezider", "Želislav", "Dezidera", "Želislava"],
  [
    "Perla",
    "Ron",
    "Ronald",
    "Zoro",
    "Zoroslav",
    "Eulália",
    "Slavena",
    "Solveiga",
    "Zoroslava",
  ],
  ["Arpád", "Jordán", "Jordána"],
  ["Valentín", "Velimír"],
  ["Pravoslav", "Faust", "Faustína", "Georgia", "Georgína", "Pravoslava"],
  ["Ida", "Liana", "Pamfil", "Pamfília"],
  [
    "Miloslava",
    "Flavián",
    "Flávius",
    "Silván",
    "Silvín",
    "Flávia",
    "Milomíra",
    "Miluša",
    "Silvána",
  ],
  ["Jaromír", "Simeon", "Jaromíra", "Konkordia", "Bernadetta"],
  ["Vlasta", "Konrád", "Kurt"],
  [
    "Lívia",
    "Aladár",
    "Lívio",
    "Lívius",
    "Udo",
    "Ulrich",
    "Alma",
    "Ulrika",
    "Ulriška",
    "Aimee",
  ],
  ["Eleonóra"],
  ["Etela", "Etel"],
  ["Roman", "Romana", "Romina"],
  [
    "Matej",
    "Jazmína",
    "Goran",
    "Mateja",
    "Matias",
    "Mateo",
    "Matiáš",
    "Yasmine",
    "Jasmína",
  ],
  ["Frederik", "Frederika", "Taras", "Federika"],
  ["Viktor", "Porfýr", "Edina"],
  [
    "Alexander",
    "Leander",
    "Sandro",
    "Skender",
    "Drahotína",
    "Dražica",
    "Leandra",
  ],
  ["Zlatica", "Elemír", "Elo", "Lumír", "Zlata"],
  ["Radomír", "Radomíra"],
];

const march = [
  ["Albín"],
  ["Anežka"],
  ["Bohumil", "Bohumila", "Ticián", "Ginda", "Kunigunda", "Ticiána"],
  ["Kazimír", "Kevin", "Gerazim", "Romeo", "Jadrana", "Kazimíra"],
  ["Fridrich", "Lucius", "Teofil", "Friderika", "Teofila"],
  [
    "Radoslav",
    "Radoslava",
    "Fridolín",
    "Koriolán",
    "Radislav",
    "Felícia",
    "Fridolína",
    "Radislava",
  ],
  ["Tomáš", "Tomislav", "Tomáška", "Tomislava"],
  ["Alan", "Alana"],
  ["Františka", "Erhard"],
  ["Branislav", "Bruno", "Bratislav", "Bronislav", "Bratislava", "Taras"],
  ["Angela", "Angelika", "Angel", "Volfram", "Algelína", "Jurina"],
  ["Gregor", "Teofan", "Gregora", "Gregoria", "Gregorína"],
  ["Vlastimil", "Kira", "Rozína"],
  ["Matilda", "Metaneta"],
  [
    "Svetlana",
    "Agap",
    "Belomír",
    "Rodan",
    "Roderich",
    "Roderik",
    "Torkvát",
    "Agapa",
    "Agapia",
    "Rodana",
    "Roderika",
  ],
  ["Boleslav", "Amos", "Bolemír", "Heribert", "Bolemíra"],
  ["Ľubica", "Ľuban", "Ľuben", "Zbignev", "Zbyšek", "Ľuba"],
  ["Eduard", "Ctislav", "Salvátor", "Ctislava", "Eduarda"],
  ["Jozef", "Sibyla"],
  ["Víťazoslav", "Klaudián", "Klaudín", "Klaudio", "Klaudius", "Víťazoslava"],
  ["Blahoslav", "Blahoboj", "Blahosej", "Radek", "Radko"],
  [
    "Beňadik",
    "Benedikt",
    "Oktavián",
    "Oktávius",
    "Benedikta",
    "Benilda",
    "Benita",
    "Izolda",
    "Oktávia",
  ],
  ["Adrián", "Apián", "Dárius", "Viktorián", "Apia"],
  ["Gabriel"],
  ["Marián", "Humbert", "Anunciáta", "Irida", "Irisa"],
  ["Emanuel", "Eman", "Manuel", "Emanuela", "Manuela"],
  ["Alena", "Rupert", "Ruprecht", "Dita", "Leia"],
  ["Soňa", "Ilarion"],
  ["Miroslav", "Mieroslav", "Bertold", "Bertolda", "Mieroslava"],
  ["Vieroslava", "Vieroľub", "Vieromil", "Vieroslav"],
  ["Benjamín", "Kvído", "Balbína"],
];
const april = [
  ["Hugo", "Hugolín"],
  ["Zita", "Áron"],
  ["Richard", "Richarda"],
  ["Izidor", "Izidora"],
  ["Miroslava", "Mira"],
  ["Irena", "Irína", "Celestín", "Ruben", "Sixtus", "Celestína", "Venuša"],
  [
    "Zoltán",
    "Armand",
    "Herman",
    "Rufínus",
    "Rúfus",
    "Armanda",
    "Rufína",
    "Rumjana",
  ],
  [
    "Albert",
    "Albertín",
    "Albrecht",
    "Valter",
    "Alberta",
    "Albertína",
    "Albrechta",
  ],
  ["Milena", "Erhard", "Mileva"],
  ["Igor", "Ezechiel", "Ivar", "Ivor", "Radomil", "Igora", "Radomila"],
  ["Július", "Antip", "Ariel", "Ariela", "Arleta", "Leo", "Lev"],
  ["Estera", "Aster", "Davorín", "Zenon", "Astéria"],
  ["Aleš", "Artem", "Artemon", "Artemia", "Artemida", "Norma"],
  ["Justína", "Hrdoslav", "Hrdoš", "Justín", "Davorína", "Hrdoslava", "Justa"],
  ["Fedor", "Fedora"],
  ["Dana", "Danica"],
  ["Rudolf", "Ralf", "Rolf", "Rudolfa", "Rudolfína", "Rudko"],
  ["Valér", "Apolón", "Erich", "Verner", "Ilma"],
  ["Jela", "Krescenc", "Krescencia"],
  ["Marcel", "Hvezdoň"],
  [
    "Ervín",
    "Abelard",
    "Adelard",
    "Anzelm",
    "Žitoslav",
    "Anzelma",
    "Ervína",
    "Saskia",
    "Žitoslava",
    "Elissa",
  ],
  ["Slavomír", "Slávo", "Tvrdomír", "Jelena", "Noema"],
  ["Vojtech", "Adalbert", "Roger", "Adalberta", "Vojtecha", "Vojteška"],
  [
    "Juraj",
    "Fidél",
    "Gaston",
    "Georg",
    "Helmut",
    "Jorik",
    "Jürgen",
    "Deora",
    "Fidélia",
    "Jorga",
    "Jorika",
    "Juraja",
  ],
  ["Marek", "Mayjoe", "Izmael", "Marko", "Markus", "Marco"],
  ["Jaroslava"],
  ["Jaroslav", "Aristid", "Tulius", "Aristída", "Tulia"],
  ["Jarmila", "Prudencius", "Prudencia"],
  ["Lea", "Timon"],
  [
    "Anastázia",
    "Anastáz",
    "Blahomil",
    "Asia",
    "Blahomila",
    "Nasťa",
    "Nastasia",
  ],
];

const may = [
  ["-", "Amarila", "Pamela"],
  ["Žigmund", "Atanáz", "Atanázia", "Aténa"],
  ["Galina", "Timea", "Horác", "Desana", "Halina"],
  ["Florián", "Flór", "Aglája", "Floriána", "Florína", "Pelagia"],
  ["Lesana", "Gothard", "Pius", "Lesia", "Pia", "Toska"],
  [
    "Hermína",
    "Ovídius",
    "Radivoj",
    "Tankréd",
    "Elfrída",
    "Frída",
    "Herina",
    "Mineta",
  ],
  ["Monika", "Napoleon", "Stanimír", "Mona"],
  ["Ingrida", "Ina", "Inga"],
  ["Roland", "Rolanda", "Christopher"],
  ["Viktória", "Armín", "Armína", "Beatrica"],
  ["Blažena", "Miranda", "Svatava"],
  ["Pankrác", "Achiles"],
  [
    "Servác",
    "Chraniboj",
    "Chranibor",
    "Chranislav",
    "Servián",
    "Chranislava",
    "Imelda",
    "Konzuela",
  ],
  ["Bonifác"],
  ["Žofia", "Brenda", "Raisa", "Sofia", "Zosia", "Sophia", "Sophie"],
  ["Svetozár", "Peregrín", "Peregrína"],
  ["Gizela", "Andronik", "Ditmar", "Paskal", "Andronika", "Paskália"],
  ["Viola"],
  ["Gertrúda", "Gerda"],
  [
    "Bernard",
    "Bernardín",
    "Hviezdoslav",
    "Bernadeta",
    "Bernarda",
    "Bernardína",
    "Hviezdoslava",
  ],
  [
    "Zina",
    "Dobromír",
    "Hostimil",
    "Hostirad",
    "Hostislav",
    "Hostisvit",
    "Teobald",
    "Dobromíra",
    "Hostimila",
    "Hostislava",
  ],
  ["Júlia", "Juliana", "Liana", "Rita"],
  ["Želmíra", "Želmír", "Želimír"],
  ["Ela", "Ella", "Elora"],
  ["Urban", "Vanesa"],
  ["Dušan"],
  ["Iveta", "Vadim", "Valdemar", "Valdemara"],
  ["Viliam", "Vilhelm", "Elektra", "Elma", "Vilhelmína", "William"],
  ["Vilma", "Elmar", "Maxim", "Maxima"],
  ["Ferdinand", "Neander", "Ferdinanda"],
  [
    "Petrana",
    "Petronela",
    "Petrónius",
    "Blahoslav",
    "Nela",
    "Petrónia",
    "Nelly",
  ],
];
const june = [
  ["Žaneta"],
  [
    "Oxana",
    "Xénia",
    "Karmen",
    "Karmena",
    "Erazim",
    "Erazmus",
    "Jaromil",
    "Vlastimila",
  ],
  [
    "Karolína",
    "Kevin",
    "Lino",
    "Linus",
    "Palmíro",
    "Kaja",
    "Klotilda",
    "Lina",
    "Lineta",
    "Palmíra",
  ],
  ["Lenka", "Lena"],
  ["Laura", "Dorotej", "Fatima", "Laurencia", "Loreta", "Loriána"],
  ["Norbert", "Norman", "Romulus", "Norberta", "Perzida"],
  [
    "Róbert",
    "Borislav",
    "Robin",
    "Teodot",
    "Dalma",
    "Oriána",
    "Róberta",
    "Robina",
    "Silver",
  ],
  ["Medard"],
  ["Stanislava", "Felicián", "Prímus", "Vojeslav", "Berenika", "Vojeslava"],
  ["Margaréta", "Gréta"],
  [
    "Dobroslava",
    "Barnabáš",
    "Dobrava",
    "Dobrota",
    "Dobrotína",
    "Flóra",
    "Pavoslava",
  ],
  [
    "Zlatko",
    "Svätoslav",
    "Svetislav",
    "Svetoslav",
    "Zlatan",
    "Zlatomír",
    "Zlatoň",
    "Zlatoš",
    "Svätoslava",
    "Svetislava",
    "Svetoslava",
    "Zlatana",
    "Zlatomíra",
  ],
  ["Anton", "Genadij", "Tobiáš", "Tobias"],
  [
    "Vasil",
    "Bazil",
    "Elizej",
    "Kvintilián",
    "Kvintín",
    "Kvintus",
    "Herta",
    "Kvinta",
    "Kvintiliána",
  ],
  ["Vít", "Jolana"],
  ["Bianka", "Blanka", "Benon", "Božetech", "Alina", "Božetecha"],
  ["Adolf", "Adolfína"],
  [
    "Vratislav",
    "Leontín",
    "Milovan",
    "Milovín",
    "Sedrik",
    "Leontína",
    "Milovana",
  ],
  ["Alfréd", "Leonid", "Leonídas", "Leoš", "Ruslan", "Alfréda"],
  ["Valéria", "Florencián", "Florentín", "Silver", "Florencia", "Florentína"],
  ["Alojz", "Elvis", "Lejla"],
  ["Paulína", "Achác", "Eberhard", "Paulín", "Paula", "Rozvita", "Zaira"],
  ["Sidónia", "Sidón"],
  ["Ján", "Janis", "Jaško", "Jens", "Johan", "Jovan", "Nino", "Sean"],
  ["Tadeáš", "Olívia", "Olívius", "Prosper", "Febrónia", "Oliva"],
  ["Adriána", "Stojan", "Adriena", "Ria", "Riana", "Stojana"],
  ["Ladislav", "Ladislava", "Samson", "Sulamita"],
  ["Beáta", "Beátus", "Slavoj", "Bea"],
  ["Peter", "Pavol", "Petra", "Pavel", "Pavla", "Petula"],
  ["Melánia", "Vlastibor", "Vlastimír", "Šárka", "VlastimíraAYLIN"],
];
const july = [
  [
    "Diana",
    "Dean",
    "Dejan",
    "Dina",
    "Zian",
    "Dajana",
    "Deana",
    "Kalina",
    "Tabita",
  ],
  ["Berta", "Bertín", "Bertína"],
  [
    "Miloslav",
    "Irenej",
    "Miliduch",
    "Milomír",
    "Milorad",
    "Radimír",
    "Rodimír",
    "Radimíra",
  ],
  ["Prokop", "Procius", "Prokopa"],
  ["Cyril", "Metod", "Cyrus", "Cyrila"],
  ["Patrik", "Patrícia", "Patrokles"],
  [
    "Oliver",
    "Donald",
    "Kastor",
    "Veleslav",
    "Velislav",
    "Valibals",
    "Veleslava",
    "Velislava",
  ],
  ["Ivan", "Ivo", "Kilián", "Perikles"],
  ["Lujza", "Lukrécius", "Lizelota", "Lukrécia"],
  ["Amália", "Amína", "Lada"],
  ["Milota", "Milutín"],
  ["Nina", "Fortunát", "Fortunáta"],
  ["Margita", "Arne", "Borivoj", "Merkéta"],
  ["Kamil"],
  [
    "Henrich",
    "Egon",
    "Enrik",
    "Enriko",
    "Henrik",
    "Henrika",
    "Lota",
    "Šarlota",
  ],
  ["Drahomír", "Karmela", "Rút", "Rúta"],
  ["Bohuslav", "Božislav", "Svorad"],
  ["Kamila", "Rowa"],
  ["Dušana"],
  ["Eliáš", "Iľja", "Ilia", "Eliána", "Iliana", "Elisa"],
  ["Daniel", "Dan", "Dalina"],
  ["Magdaléna", "Magda", "Mahuliena", "Majda"],
  [
    "Oľga",
    "Apolinár",
    "Libérius",
    "Libor",
    "Liborius",
    "Apolinára",
    "Libora",
    "Lilien",
  ],
  ["Vladimír", "Kinga"],
  ["Jakub", "Žakelína"],
  ["Anna", "Hana", "Aneta", "Anica", "Anita", "Annamária", "Naneta", "Joachim"],
  ["Božena", "Gorazd", "Pantaleon"],
  [
    "Krištof",
    "Inocent",
    "Svätomír",
    "Svätoš",
    "Inocencia",
    "Nausika",
    "Svätomíra",
  ],
  ["Marta", "Olaf", "Serafín", "Serafa", "Serafína"],
  ["Libuša", "Abdon", "Ingemar", "Ingeborga", "Ľubuša", "Rowena"],
  ["Ignác", "Ignát", "Vatroslav", "Ignácia"],
];
const august = [
  [
    "Božidara",
    "Božidar",
    "Ľudomír",
    "Božica",
    "Kleopatra",
    "Ľudomíra",
    "Penelopa",
  ],
  ["Gustáv", "Gustáva"],
  ["Jerguš", "Nikodém", "Nikodéma"],
  ["Dominik", "Dominika", "Krasoslav", "Rainer", "Krasoslava", "Donna"],
  ["Hortenzia", "Hortenz", "Milivoj", "Osvald", "Snežana"],
  ["Jozefína", "Nehoslav", "Jozefa"],
  ["Štefánia", "Kajetán", "Afra", "Afrodita", "Kajetána", "Štefana"],
  ["Oskár", "Donát", "Hartvig", "Virgín", "Donáta", "Virgínia"],
  ["Ľubomíra", "Rastic"],
  ["Vavrinec", "Lars", "Laurenc", "Laurus", "Lorenc", "Vavro"],
  ["Zuzana", "Trojan", "Dulcia", "Dulcinela", "Dulcínia"],
  ["Darina", "Dárius", "Dária"],
  ["Ľubomír", "Hypolit", "Kasián", "Kasius", "Belinda"],
  ["Mojmír", "Eusébius", "Mojtech", "Eusébia"],
  ["Marcela"],
  ["Leonard", "Jáchim", "Joachim", "Linhart", "Rochus", "Leonarda"],
  ["Milica", "Bertram", "Bertrand", "Hyacint", "Libert", "Miron", "Hyacinta"],
  ["Elena", "Helena", "Ilona", "Aylin"],
  ["Lýdia", "Vratislava", "Lilien"],
  ["Anabela", "Arabela", "Liliana"],
  ["Jana", "Janka", "Johana", "Jovana"],
  ["Tichomír", "Sigfríd", "Tichomil", "Tichomíra"],
  ["Filip", "Vlastislav", "Filipa", "Filipína", "Vlastislava"],
  ["Bartolomej", "Bartolomea"],
  ["Ľudovít", "Ludvig", "Radim", "Ľudovíta"],
  ["Samuel", "Samo", "Zemfír", "Samuela", "Tália", "Zemfíra"],
  ["Silvia", "Silvio", "Silvius"],
  ["Augustín", "August", "Augusta", "Augustína", "Gustína"],
  ["Nikola", "Nikolaj", "Koleta", "Nikoleta", "(Nikolas)"],
  ["Ružena", "Ružica"],
  ["Nora", "Rajmund", "Ramón", "Rajmunda", "Ramona"],
];
const september = [
  ["Drahoslava", "Egid", "Egídius", "Deborah"],
  ["Linda", "Absolón", "Axel", "Justus", "Ermelinda", "Melinda", "Rebeka"],
  ["Belo", "Antim", "Klélia"],
  [
    "Rozália",
    "Kandid",
    "Mojžiš",
    "Rozalín",
    "Rozálio",
    "Kandida",
    "Róza",
    "Rozeta",
    "Rozita",
    "Rusalka",
  ],
  [
    "Regína",
    "Bojan",
    "Bojimír",
    "Bojislav",
    "Borimír",
    "Branimír",
    "Chotimír",
    "Justinián",
    "Otakar",
    "Regan",
    "Regulus",
    "Viktorín",
    "Bojana",
    "Bojimíra",
    "Boislava",
    "Branimíra",
    "Budislava",
    "Chotimíra",
    "Larisa",
  ],
  ["Alica", "Brian", "Magnus", "Mansvét", "Zachariáš", "Bria", "Larisa"],
  ["Marianna", "Mariana"],
  ["Miriama", "Miriana"],
  ["Martina", "Gordan", "Gordián", "Gordon", "Omar", "Gordana", "Rea", "Tina"],
  ["Oleg", "Honór", "Vitold", "Honóra", "Krasava", "Vitolda"],
  ["Bystrík", "Prótus", "Zdislav", "Helga", "Zdislava"],
  [
    "Mária",
    "Maja",
    "Manon",
    "Manona",
    "Marica",
    "Mariela",
    "Marieta",
    "Marika",
    "Marila",
    "Mariola",
    "Marlena",
    "Marusia",
    "Jessica",
    "Mia",
  ],
  ["Ctibor", "Amát", "Amátus", "Stibor", "Sven", "Amáta", "Tobias"],
  [
    "Ľudomil",
    "Dragan",
    "Dragutín",
    "Drahan",
    "Drahotín",
    "Ľudomila",
    "Radka",
    "Serena",
  ],
  ["Jolana", "Melissa", "Melisa", "Melita"],
  ["Ľudmila", "Dunja"],
  ["Olympia", "Lambert", "Záviš"],
  ["Eugénia", "Ariadna"],
  ["Konštantín", "Trofín", "Konstancia", "Konštantína"],
  [
    "Ľuboslav",
    "Ľuboslava",
    "Eustach",
    "Filibert",
    "Liboslav",
    "Eustachia",
    "Liboslava",
  ],
  ["Matúš", "Ifigénia", "Mirela"],
  ["Móric", "Maurícius", "Maurus"],
  ["Zdenka", "Polyxénia", "Tekla", "Zdena"],
  ["Ľubor", "Ľuboš", "Terenc"],
  ["Vladislav", "Vladivoj", "Eufrozina", "Fruzína", "Vladislava", "Jesika"],
  ["Edita", "Damián", "Kozmas", "Damiána"],
  ["Cyprián", "Mirabela"],
  ["Václav", "Chariton", "Kariton", "Václava"],
  ["Michal", "Michaela", "Michael", "Michala"],
  ["Jarolím", "Hieronym", "Jeremiáš", "Jarolíma", "Ráchel", "Ráchela", "Una"],
];
const october = [
  ["Arnold", "Remig", "Remus", "Arnolda", "Belina"],
  ["Levoslav", "Leodegar", "Levoslava"],
  ["Stela", "Amadeus", "Evald", "Amadea"],
  ["František", "Edvin", "Fraňo"],
  ["Viera", "Blahomír", "Placid", "Blahomíra", "Karitína", "Placida"],
  ["Natália"],
  ["Eliška"],
  ["Brigita", "Brit", "Brita"],
  ["Dionýz", "Dionýzia"],
  ["Slavomíra", "Gedeon", "Záboj", "Krasomila"],
  [
    "Valentína",
    "Belín",
    "Zvonimír",
    "Zvonislav",
    "Bruna",
    "Brunhilda",
    "Luneta",
    "Selena",
    "Zvonimíra",
    "Zvonislava",
  ],
  ["Maximilián", "Max", "Maximiliána"],
  ["Koloman", "Edgar"],
  ["Boris", "Borislav", "Kalist", "Borislava", "Kalista"],
  ["Terézia", "Tereza"],
  ["Vladimíra", "Gál", "Havel", "Havla"],
  ["Hedviga", "Jadviga"],
  ["Lukáš"],
  ["Kristián", "Christián", "Izák", "Christiána", "Kristiána"],
  ["Vendelín", "Eunika", "Vendelína"],
  ["Uršuľa", "Anatol", "Anatólia", "Antília"],
  [
    "Sergej",
    "Dobromil",
    "Sergius",
    "Zdravomil",
    "Kordula",
    "Korduľa",
    "Pribislava",
    "Saloma",
    "Saloména",
    "Solomia",
  ],
  ["Alojzia", "Žitomír"],
  [
    "Kvetoslava",
    "Aretas",
    "Cvetan",
    "Gilbert",
    "Harold",
    "Herald",
    "Krasomil",
    "Kvetoň",
    "Kvetoslav",
    "Rafael",
    "Šalamún",
    "Areta",
    "Cvetana",
    "Gilberta",
    "Kveta",
    "Kvetana",
    "Kvetava",
    "Rafaela",
  ],
  [
    "Aurel",
    "Krišpín",
    "Vojmír",
    "Zosim",
    "Živan",
    "Živko",
    "Dália",
    "Vojmíra",
    "Živa",
    "Živana",
  ],
  ["Demeter", "Amand", "Dimitrij", "Evarist", "Amanda", "Demetria"],
  [
    "Sabína",
    "Horislav",
    "Hromislav",
    "Horislava",
    "Hromislava",
    "Sabrina",
    "Zoa",
    "Zoana",
  ],
  ["Dobromila", "Kevin"],
  ["Klára", "Narcis", "Zenob", "Klarisa", "Narcisa", "Zenóbia", "Chiara"],
  ["Šimon", "Simona", "Arzen", "Asen", "Simon", "Asena", "Simoneta", "Šimona"],
  ["Aurélia", "Stacho", "Volfgang"],
];
const november = [
  ["Denis", "Denisa"],
  ["-", "Cézar", "Cezária"],
  ["Hubert"],
  ["Karol", "Džesika", "Jesika", "Karola", "Skarleta", "Jessica", "Yessica"],
  ["Imrich", "Emerich", "Imriška"],
  ["Renáta", "Renát", "Renáto", "Renátus"],
  ["René", "Engelbert"],
  ["Bohumír", "Bohumíra"],
  [
    "Teodor",
    "Orest",
    "Teo",
    "Teodorik",
    "Teodoz",
    "Deodata",
    "Tea",
    "Teodora",
    "Teodózia",
  ],
  ["Tibor", "Tiber", "Meluzína", "Tibora", "Tobias"],
  ["Martin", "Maroš", "Martinián"],
  ["Svätopluk", "Astrid", "Jonáš", "Astrida"],
  ["Stanislav", "Orin"],
  [
    "Irma",
    "Juventín",
    "Mladen",
    "Mladoň",
    "Mladotín",
    "Ima",
    "Juventína",
    "Mladena",
    "Mladotína",
  ],
  ["Leopold", "Leopolda", "Leopoldína"],
  ["Agnesa", "Otmar", "Agneša", "Inéza"],
  ["Klaudia", "Klodeta"],
  ["Eugen", "Platón"],
  [
    "Alžbeta",
    "Betina",
    "Elizabeta",
    "Elizabeth",
    "Lila",
    "Liliana",
    "Líza",
    "Lili",
    "Lilly",
    "Lily",
  ],
  ["Félix", "Filemon", "Homér"],
  ["Elvíra", "Ctirad", "Ctirada"],
  ["Cecília", "Cecilián", "Šejla"],
  ["Klement", "Klementín", "Kliment", "Kolumbín", "Klementína", "Kolumbína"],
  ["Emília", "Milín", "Milina"],
  ["Katarína", "Katrina"],
  ["Kornel", "Valerián"],
  ["Milan", "Nestor", "Virgil", "Milana"],
  ["Henrieta", "Gerhard", "Tristan", "Desdemona", "Eta"],
  ["Vratko", "Saturnín", "Zaida"],
  ["Andrej", "Ondrej", "Andreas"],
];
const december = [
  ["Edmund", "Edmunda"],
  ["Bibiána", "Budimír", "Budislav", "Budimíra", "Vivien"],
  ["Oldrich", "Sofron", "Xavér", "Sofrónia", "Xavéria"],
  ["Barbora", "Babeta", "Barbara", "Barica"],
  [
    "Oto",
    "Gerald",
    "Otakar",
    "Otokar",
    "Geralda",
    "Geraldína",
    "Jitka",
    "Ota",
    "Sáva",
  ],
  ["Mikuláš", "Nikita", "Niko", "Nikolas", "Mikuláška", "Nikoleta"],
  ["Ambróz", "Amarant", "Amaranta", "Ambrózia"],
  ["Marína"],
  ["Izabela", "Dalila", "Leokádia"],
  ["Radúz", "Herbert"],
  ["Hilda", "Hildegard", "Hildegarda"],
  ["Otília", "Spiridon", "Dília", "Odeta"],
  ["Lucia", "Rosan", "Rosana", "Roxana"],
  ["Branislava", "Bronislava", "Broňa"],
  ["Ivica", "Detrich", "Radan", "Radana"],
  ["Albína", "Bela", "Teofánia"],
  ["Kornélia", "Lazár", "Kora", "Korina"],
  ["Sláva", "Slávka", "Gracián", "Grácia", "Graciána", "Slavislava"],
  ["Judita", "Abrahám", "Mstislav", "Neméz", "Ita", "Mstislava", "Neméza"],
  ["Dagmara", "Dagmar", "Dag", "Dagobert", "Daga", "Damara"],
  ["Bohdan"],
  ["Adela", "Ada", "Adelaida", "Adelgunda", "Adelína", "Adina", "Alida"],
  ["Nadežda", "Naďa"],
  ["Adam", "Eva", "Evamária", "Evelína", "Gaja", "Gajana", "Geja"],
  ["Lilith"],
  ["Štefan"],
  ["Filoména", "Filomén"],
  ["Ivana", "Ivona", "Iva"],
  ["Milada", "Jonatán", "Miladín", "Nátan", "Natanel"],
  ["Dávid", "Lotar"],
  ["Silvester", "Horst"],
];

const namedays = [
  january,
  february,
  march,
  april,
  march,
  june,
  july,
  august,
  september,
  october,
  november,
  december,
];

export const namedayToday = () => {
  const date = new Date();
  const day = date.getDate() - 1;
  const month = date.getMonth();

  return namedays[month][day] || [];
};

let counter = 0;
export const nextNameday = () => {
  const names = namedayToday();
  if (counter >= names.length) {
    counter = 0;
  }

  const name = names[counter];
  counter++;

  return name || "";
};
